apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      volumes:
        - name: mongodb-data
          awsElasticBlockStore:
            volumeID: vol-085c183970045ce1c
            fsType: ext4
      containers:
        - image: mongo
          name: mongodb
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      nodeSelector:
        kubernetes.io/hostname: i-0d31883ee7a15fc70


# db.movie.insert({"name":"Fast & Furious 1"})
# db.movie.insert({"name":"Fast & Furious 2"})
# db.movie.insert({"name":"Fast & Furious 3"})
# db.movie.insert({"name":"Fast & Furious 4"})
# db.movie.insert({"name":"Fast & Furious 5"})
# db.movie.insert({"name":"Fast & Furious 6"})

# > show dbs
# > show collections
# > db.movie.find()