apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: emptydir
          emptyDir:
            sizeLimit: 50Mi
            medium: "Memory"
      containers:
        - name: troubleshooting
          image: kiran2361993/troubleshootingtools:v1
          volumeMounts:
            - name: emptydir
              mountPath: /etc/myemptydir
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp/myemptydir
              name: emptydir