apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb
          imagePullPolicy: Always
          volumeMounts:
            - name: mongodb-data1
              mountPath: /data/db
            - name: mongodb-data2
              mountPath: /tmp/db1
            - name: mongodb-data3
              mountPath: /tmp/db2
            - name: mongodb-data4
              mountPath: /tmp/db3
      volumes:
        - name: mongodb-data1
          persistentVolumeClaim:
            claimName: task-pv-claim1
        - name: mongodb-data2
          persistentVolumeClaim:
            claimName: task-pv-claim2
        - name: mongodb-data3
          persistentVolumeClaim:
            claimName: task-pv-claim3
        - name: mongodb-data4
          persistentVolumeClaim:
            claimName: task-pv-claim4
      nodeSelector:
        kubernetes.io/hostname: i-099b16a7884f9c901