- name: NGINX Configuration
  hosts: all
  become: yes
  tasks:
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: latest
    - name: Start NGINX
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

- name: Docker Configuration
  hosts: all
  become: yes
  roles:
    - docker
