- name: Ansible Conditions.
  hosts: all
  connection: local
  vars:
    fruit: true
    vegetables: false
  tasks:
    -  name: Fruit List
       ansible.builtin.debug:
         msg: Fruit name is - Apple
       when: fruit == true
    # We can also define like when: fruit is true

    - name: Vegetable List
      ansible.builtin.debug:
        msg: Vegetable Name is - Carrot
      when: vegetables == true
