apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: example
spec:
  limits:
    - type: Container
      defaultRequest: # this section defines default requests
        memory: "128Mi"
        cpu: "200m"
      default: # this section defines default limits
        memory: "256Mi"
        cpu: "400m"
      max: # max and min define the limit range
        memory: "800Mi"
        cpu: "1000m"
      min:
        memory: "100Mi"
        cpu: "150m"
