apiVersion: "v1"
kind: "Namespace"
metadata:
  labels:
    kubernetes.io/metadata.name: "alpha"
  name: "alpha"
spec:
  finalizers:
    - "kubernetes"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "ludo-game"
  name: "ludo-game"
  namespace: "alpha"
spec:
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "ludo-game"
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "ludo-game"
    spec:
      containers:
        - image: "kiran2361993/kubegame:v1"
          name: "kubegame"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: "external" # Required for ALB
  service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # For public ALB, or "internal" for private ALB
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "HTTP"
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:REGION:ACCOUNT_ID:certificate/CERTIFICATE_ID"
  service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
  labels:
    app: "ludo-game"
  name: "ludo-game"
  namespace: "alpha"
spec:
  type: "LoadBalancer"
  selector:
    app: "ludo-game"
  ports:
    - name: "http" # Added port name for HTTP
      port: 80
      protocol: "TCP"
      targetPort: 80
    - name: "https" # Added port name for HTTPS
      port: 443
      protocol: "TCP"
      targetPort: 80
