apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: singtel
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
