#Creating Namespaces & Utilpods

#Creating Namespaces
kubectl create ns prod
kubectl create ns dev
kubectl create ns qa
  
#Labling Namespaces
kubectl label ns prod nsp=prod
kubectl label ns dev nsp=dev
kubectl label ns qa nsp=qa
  
#Deploy  pod in all namespaces
kubectl run -n prod prod1 --image=kiran2361993/troubleshootingtools:v1 -l ns=prod
kubectl run -n prod prod2 --image=kiran2361993/troubleshootingtools:v1 -l ns=prod
    
kubectl run -n dev dev1 --image=kiran2361993/troubleshootingtools:v1 -l ns=dev
kubectl run -n dev dev2 --image=kiran2361993/troubleshootingtools:v1 -l ns=dev
    
kubectl run -n qa qa1 --image=kiran2361993/troubleshootingtools:v1 --labels ns=qa
kubectl run -n qa qa2 --image=kiran2361993/troubleshootingtools:v1 --labels ns=qa

kubectl get po -n prod -o wide --no-headers && kubectl get po -n dev -o wide --no-headers && kubectl get po -n qa -o wide --no-headers
    
alias allpods='kubectl get po -n prod -o wide --no-headers && kubectl get po -n dev -o wide --no-headers && kubectl get po -n qa -o wide --no-headers'
    
    
# Check the ping status.    
kubectl exec -it  prod1 -n prod -- ping -c 3  100.106.150.83 \
&& kubectl exec -it  prod2 -n prod -- ping -c 3  100.97.52.10 \
&& kubectl exec -it  prod1 -n prod -- ping -c 3   100.106.150.84 \
&& kubectl exec -it  prod2 -n prod -- ping -c 3   100.99.93.24
    
    
kubectl exec -it  dev1 -n dev -- ping -c 3    100.106.150.84 \
&& kubectl exec -it  dev2 -n dev -- ping -c 3  100.99.93.24 \
&& kubectl exec -it  dev1 -n dev -- ping -c 3   100.99.93.22 \
&& kubectl exec -it  dev2 -n dev -- ping -c 3 100.99.93.23
    
    
kubectl exec -it  qa1 -n qa -- ping -c 3     100.99.93.22  \
&& kubectl exec -it  qa2 -n qa -- ping -c 3   100.99.93.23  \
&& kubectl exec -it  qa1 -n qa -- ping -c 3  100.106.150.83 \
&& kubectl exec -it  qa2 -n qa -- ping -c 3   100.97.52.10