- name: Install New Relic
  hosts: all
  become: yes
  vars:
    newrelic_api_key: xxxxxxxxxxxxxxxxxxxxxxxxx
    newrelic_account_id: xxxxxxx

  tasks:
    - name: Check if New Relic service is running
      shell: systemctl is-active newrelic-infra
      register: newrelic_service_status
      failed_when: false
      changed_when: false

    - name: Skip installation if New Relic is running
      debug:
        msg: "New Relic is already installed and running. Skipping installation."
      when: newrelic_service_status.stdout == "active"
      tags: skip

    - name: Refresh all repositories
      shell: zypper refresh
      register: refresh_output
      ignore_errors: true
      when: newrelic_service_status.stdout != "active"
      # no_log: true

    - name: Parse problematic repositories from refresh output
      shell: |
        echo "{{ refresh_output.stderr }}" | grep -oP '(?<=Repository ).*?(?= is invalid|refresh failed)' | awk '{print $1}'
      register: problematic_repos
      changed_when: false
      when: newrelic_service_status.stdout != "active"

    - name: Disable problematic repositories
      shell: |
        zypper mr -d {{ item }}
      with_items: "{{ problematic_repos.stdout_lines }}"
      when:
        - newrelic_service_status.stdout != "active"
        - problematic_repos.stdout_lines | length > 0

    - name: Install New Relic agent
      shell: |
        curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash &&
        NEW_RELIC_API_KEY={{ newrelic_api_key }} NEW_RELIC_ACCOUNT_ID={{ newrelic_account_id }} /usr/local/bin/newrelic install < /dev/null
      when: newrelic_service_status.stdout != "active"

    - name: Re-enable problematic repositories
      shell: |
        zypper mr -e {{ item }}
      with_items: "{{ problematic_repos.stdout_lines }}"
      when:
        - newrelic_service_status.stdout != "active"
        - problematic_repos.stdout_lines | length > 0

# ansible-playbook -i inv --limit sap -e "ansible_user=xxxxxx" -e "ansible_password=xxxxxxx" /root/ansible/install_newrelic.y
#ml