---
- name: Install Apache on RHEL server
  user: root
  connection: ssh
  hosts: devops
  tasks:
   -    name: Add a list of users.
        user: name='{{item}}' state=present
        with_items:
                - Abhi
                - Debi
                - shahid