---
        - name: lvm create
          hosts: server
          user: root
          become: yes
          connection: ssh
          tasks:
                - name: Create Partition
                  parted:
                        device: /dev/sdb
                        number: 2
                        flags: [lvm]
                        state: present
                        part_start: 1GiB

