---
- name: Disable firewalld, SELinux, install packages, and configure logrotate on CentOS 9
  hosts: all
  become: true
  tasks:

    - name: Stop and disable firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Ensure SELinux is disabled in config file
      ansible.builtin.replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing'
        replace: 'SELINUX=disabled'
      #when: ansible_facts['selinux']['status'] == 'enabled'

    - name: Disable SELinux enforcement for the current session
      ansible.builtin.command: setenforce 0
      ignore_errors: yes

    - name: Install required packages (nmap, telnet, git)
      ansible.builtin.yum:
        name:
          - nmap
          - telnet
          - git
        state: present

    - name: Reboot the server for SELinux changes to take effect
      ansible.builtin.reboot:
        msg: "Rebooting to apply SELinux disabled mode"
        reboot_timeout: 300
      when: ansible_connection != 'local'

    - name: Copy logrotate configuration for /var/log/messages
      ansible.builtin.copy:
        dest: /etc/logrotate.d/messages
        content: |
          /var/log/messages {
              weekly
              rotate 4
              dateext
              delaycompress
              compress
              missingok
              notifempty
              postrotate
                  /bin/systemctl reload rsyslog > /dev/null 2>&1 || true
              endscript
          }

    - name: Set ownership and permissions for logrotate file
      ansible.builtin.file:
        path: /etc/logrotate.d/messages
        owner: root
        group: root
        mode: '0644'
