apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |
    [defaults]
    aws_access_key_id: AKIA5V6I7CDHBKHWXIAS
    aws_secret_access_key: 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
    region: "us-east-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshootingtools-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshootingtools
  template:
    metadata:
      labels:
        app: troubleshootingtools
    spec:
      containers:
        - name: troubleshootingtools
          image: kiran2361993/troubleshootingtools:v1
          volumeMounts:
            - name: aws-credentials-volume
              mountPath: /root/.aws/credentials
              subPath: credentials
              readOnly: false
      volumes:
        - name: aws-credentials-volume
          secret:
            secretName: aws-credentials