# Pod-Based Node Selector
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-web
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        disk: ssd
        env: dev
      containers:
        - image: nginx:1.14
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
      terminationGracePeriodSeconds: 120
---
# Name Space-Based.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-test
  namespace: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.14
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
      terminationGracePeriodSeconds: 120