# In one node only one redis and one nginx pod should present.
# Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: webserver-db
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: docker.io/redis:7.2
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
            - containerPort: 6379
      terminationGracePeriodSeconds: 120
---
# Web
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: webserver-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis
              topologyKey: "kubernetes.io/hostname"
      # Using kubernetes.io/hostname ensures that the rule affects individual nodes.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: nginx:1.14
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
      terminationGracePeriodSeconds: 120


