- name: Catalogue Component Setup - RoboShop
  hosts: all
  become: yes
  vars:
    - component: catalogue
    - schema: true
  tasks:
    - name: Catalogue Configuration
      ansible.builtin.import_tasks: nodejs.yml

