- name: Shipping Setup - Roboshop
  hosts: all
  become: yes
  vars:
    - component: shipping
    - schema: true
  tasks:
    - name: Shipping Configuration
      ansible.builtin.import_tasks: java.yml