apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: development-RoleBinding
  namespace: development
subjects:
  - kind: User
    name: abhijeet
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: development-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: production-RoleBinding
  namespace: production
subjects:
  - kind: User
    name: abhi
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: production-role
  apiGroup: rbac.authorization.k8s.io
