apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: development-role
  namespace: development
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"] # "" indicates the core API group for eacho use '' not "".

    resources:
      ["pods", "deployments", "replicasets", "nodes", "ingress", "services"]
    verbs: ["get", "update", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: production-role
  namespace: production
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"] # "" indicates the core API group for eacho use '' not "".

    resources:
      ["pods", "deployments", "replicasets", "nodes", "ingress", "services"]
    verbs: ["get", "update", "list", "create", "delete"]