- name: Importing SSM-Agent Tasks.
  ansible.builtin.import_tasks: amazon-ssm-agent.yml

- name: Installing the Maven and MySql.
  ansible.builtin.yum:
    name:
      - maven
      - mysql
    state: installed

- name: Importing App Prerequisite Tasks.
  ansible.builtin.import_tasks: appprereq.yml

- name: Downloading Dependencies and making artifact.
  ansible.builtin.shell: mvn clean package ; mv /app/target/{{component}}-1.0.jar /app/{{component}}.jar
  args:
    chdir: /app

- name: Importing Schema Setup Tasks.
  ansible.builtin.import_tasks: mysql_schema.yml
  when: schema is defined

- name: Importing Systemd Setup Tasks.
  ansible.builtin.import_tasks: systemd.yml

