apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb
          imagePullPolicy: Always
          volumeMounts:
            - name: mongodb-data1
              mountPath: /data/db
      volumes:
        - name: mongodb-data1
          persistentVolumeClaim:
            claimName: task-pv-claim5