apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-web-pvc
  namespace: singtel
spec:
  storageClassName: nfs-storage 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
